# Generated by Django 3.1.7 on 2021-05-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210519_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Not delivered yet', max_length=255, verbose_name='status'),
        ),
    ]
