# Generated by Django 3.1.6 on 2021-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210531_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='is_shipped',
            field=models.BooleanField(default=False, verbose_name='shipped'),
        ),
    ]
