# Generated by Django 3.1.7 on 2021-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
    ]
