# Generated by Django 3.1.7 on 2021-05-03 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Home_Module.user')),
                ('shop', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_social_user', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('image1', models.ImageField(default=None, upload_to='products/images')),
                ('image2', models.ImageField(default=None, upload_to='products/images')),
                ('image3', models.ImageField(default=None, upload_to='products/images')),
                ('image4', models.ImageField(default=None, upload_to='products/images')),
                ('category', models.CharField(choices=[('men', "Men's Fashion"), ('women', "Women's Fashion"), ('WBJ', 'Watches,Bags & Jewelery')], max_length=255)),
                ('description', models.CharField(default=None, max_length=255)),
                ('sellerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
