# Generated by Django 3.1.7 on 2021-04-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDeatail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Home_Module.user')),
                ('shop', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=14)),
            ],
        ),
    ]
