# Generated by Django 3.1.7 on 2021-05-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0002_order_orderdetails_shippingdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingDetail',
        ),
    ]
