# Generated by Django 3.1.7 on 2021-04-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0002_sellerdeatail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerDeatail',
            new_name='SellerDetail',
        ),
    ]
