# Generated by Django 3.1.7 on 2021-04-20 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0003_auto_20210418_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('sellerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
