# Generated by Django 3.1.7 on 2021-05-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0003_delete_shippingdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='products',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
