# Generated by Django 3.1.7 on 2021-03-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0003_auto_20210327_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=50, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
    ]
