# Generated by Django 3.1.7 on 2021-03-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0004_auto_20210327_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
