# Generated by Django 3.1.7 on 2021-05-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0005_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='stars',
            new_name='rate',
        ),
    ]
