# Generated by Django 3.1.7 on 2021-05-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0005_auto_20210524_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(upload_to='products/images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(upload_to='products/images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(upload_to='products/images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.ImageField(upload_to='products/images'),
        ),
    ]
