# Generated by Django 3.1.7 on 2021-05-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0008_auto_20210526_0553'),
        ('Home_Module', '0006_auto_20210524_1254'),
    ]

    operations = [
    ]
