# Generated by Django 3.1.7 on 2021-04-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0008_products_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default='', upload_to='products/images'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(default='', upload_to='products/images'),
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(default='', upload_to='products/images'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
