# Generated by Django 3.1.6 on 2021-06-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0009_merge_20210526_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
