# Generated by Django 3.1.7 on 2021-04-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0009_auto_20210421_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
