# Generated by Django 3.1.6 on 2021-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0010_auto_20210605_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
