# Generated by Django 3.1.7 on 2021-05-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0012_auto_20210502_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='subcategory',
        ),
    ]
