# Generated by Django 3.1.7 on 2021-05-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0013_remove_products_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('men', "Men's Fashion"), ('women', "Women's Fashion"), ('WBJ', 'Watches,Bags & Jewelery')], max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(default=None, upload_to='products/images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(default=None, upload_to='products/images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(default=None, upload_to='products/images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.ImageField(default=None, upload_to='products/images'),
        ),
    ]
